
//Navegacion
export const VISTA_PRODUCTO = 'VISTA_PRODUCTO';
export const VISTA_HISTORIA = 'VISTA_HISTORIA';
export const VISTA_METRICAS = 'VISTA_METRICAS';
//Lista
export const LISTA_DE_PRODUCTOS = 'LISTA_DE_PRODUCTOS';
export const LIMPIEZA_CATEGORIAS_TIENDA = 'LIMPIEZA_CATEGORIAS_TIENDA';
//carrito
export const AGREGAR_PRODUCTO_CARRITO = 'AGREGAR_PRODUCTO_CARRITO';
export const INCREMENTAR_CANTIDAD_CARRITO = 'INCREMENTAR_CANTIDAD_CARRITO';
export const DECREMENTAR_CANTIDAD_CARRITO = 'DECREMENTAR_CANTIDAD_CARRITO';
export const ELIMINAR_PRODUCTO_CARRITO = 'ELIMINAR_PRODUCTO_CARRITO';
export const VISTAS_DEL_CARRITO = 'VISTAS_DEL_CARRITO';
