
//Navegacion
export const VISTA_PRODUCTO = 'VISTA_PRODUCTO';
export const VISTA_HISTORIA = 'VISTA_HISTORIA';
export const VISTA_METRICAS = 'VISTA_METRICAS';
export const VISTAS_PRODUCTOS = 'VISTAS_PRODUCTOS';

//Lista
export const LISTA_DE_PRODUCTOS = 'LISTA_DE_PRODUCTOS';
//carrito
export const AGREGAR_PRODUCTO_CARRITO = 'AGREGAR_PRODUCTO_CARRITO';
export const INCREMENTAR_CANTIDAD_CARRITO = 'INCREMENTAR_CANTIDAD_CARRITO';

